version: "2"

services:
  web:
    image: node:10-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
      - 5000:5000
    command: npm run start:dev